RESPONSES = {
    "pt": {
        "greeting": "Bom dia! Sou a Marta, a sua assistente de reservas para o restaurante Tibino. Como posso ajudar?",
        "greeting_returning": "Olá novamente! Como posso ajudar?",
        "fallback": "Peço desculpa, não entendi. Pode tentar de novo?",
        "hours_info": "Estamos abertos de Quarta a Segunda. Almoço: 12h-15h. Jantar: 19h-23h (cozinha encerra às 22h). Encerramos à Terça-feira.",
        "ask_reservation_details": "Claro! Para fazer a reserva, preciso do seu nome, número de telemóvel, dia, hora e número de pessoas.",
        "reservation_staging": "Ok, vou confirmar com a equipa.",
        "staff_whatsapp_template": "Reserva: {date_short} {time}, {name}, {phone}, {party_size} pessoas – alguém confirma?",
        "staff_confirmation_timeout": "Desculpa, agora ninguém está livre para confirmar. Tenta mais tarde ou liga.",
        "reservation_confirmed_staff": "Feito! Mesa {table_number} {date_short} às {time}. Ah, e {menu}",
        "reservation_confirmed": "A sua reserva para {party_size} pessoas no {date_short} às {time} está confirmada. Obrigado, {name}! {menu}",
        "reservation_full": "Peço desculpa, mas estamos cheios nessa altura. A primeira vaga é às {available_time}.",
        "last_reservation_time_exceeded": "Desculpe, a última reserva para o jantar é às 21:30. Deseja marcar para essa hora?",
        "cancel_prompt": "Para cancelar a sua reserva, pode indicar-me o nome ou o número de telemóvel associado?",
        "reservation_cancelled": "A sua reserva foi cancelada. Esperamos vê-lo em breve.",
        "reservation_not_found": "Não encontrei nenhuma reserva com esses dados.",
        "ask_modification_details": "Para alterar a sua reserva, pode indicar-me o nome ou o número de telemóvel?",
        "reservation_modified": "A sua reserva foi alterada com sucesso.",
        "full_menu_info": "O menu completo e a carta de vinhos estão no site: netlify.app/tibino-menu"
    },
    "en": {
        "greeting": "Good morning! I'm Marta, your booking assistant for the Tibino restaurant. How can I help you?",
        "greeting_returning": "Hello again! How can I help?",
        "fallback": "I'm sorry, I didn't understand. Can you please try again?",
        "hours_info": "We are open from Wednesday to Monday. Lunch: 12 PM-3 PM. Dinner: 7 PM-11 PM (kitchen closes at 10 PM). We are closed on Tuesdays.",
        "ask_reservation_details": "Of course! To make a reservation, I need your name, phone number, day, time, and the number of people.",
        "reservation_staging": "Ok, I will confirm with the team.",
        "staff_whatsapp_template": "Reservation: {date_short} {time}, {name}, {phone}, {party_size} people – anyone confirm?",
        "staff_confirmation_timeout": "Sorry, no one is available to confirm right now. Please try again later or call.",
        "reservation_confirmed_staff": "Done! Table {table_number} {date_short} at {time}. Also, for tomorrow's menu you have {menu}",
        "reservation_confirmed": "Your reservation for {party_size} people on {date_short} at {time} is confirmed. Thank you, {name}! {menu}",
        "reservation_full": "I'm sorry, but we are full at that time. The first available slot is at {available_time}.",
        "last_reservation_time_exceeded": "I'm sorry, the last reservation for dinner is at 9:30 PM. Would you like to book for that time?",
        "cancel_prompt": "To cancel your reservation, could you please provide the name or phone number associated with it?",
        "reservation_cancelled": "Your reservation has been cancelled. We hope to see you soon.",
        "reservation_not_found": "I couldn't find any reservation with that information.",
        "ask_modification_details": "To modify your reservation, could you please provide the name or phone number?",
        "reservation_modified": "Your reservation has been successfully modified.",
        "full_menu_info": "The full menu and wine list are on the website: netlify.app/tibino-menu"
    },
    "fr": {
        "greeting": "Bonjour! Je suis Marta, votre assistante de réservation pour le restaurant Tibino. Comment puis-je vous aider?",
        "greeting_returning": "Bonjour à nouveau! Comment puis-je aider?",
        "fallback": "Je suis désolée, je n'ai pas compris. Pouvez-vous réessayer?",
        "hours_info": "Nous sommes ouverts du mercredi au lundi. Déjeuner : 12h-15h. Dîner : 19h-23h (la cuisine ferme à 22h). Nous sommes fermés le mardi.",
        "ask_reservation_details": "Bien sûr! Pour faire une réservation, j'ai besoin de votre nom, numéro de téléphone, jour, heure et nombre de personnes.",
        "reservation_staging": "Ok, je vais confirmer avec l'équipe.",
        "staff_whatsapp_template": "Réservation : {date_short} {time}, {name}, {phone}, {party_size} personnes – quelqu'un confirme ?",
        "staff_confirmation_timeout": "Désolé, personne n'est disponible pour confirmer pour le moment. Veuillez réessayer plus tard ou appeler.",
        "reservation_confirmed_staff": "Fait ! Table {table_number} {date_short} à {time}. De plus, au menu de demain, vous avez {menu}",
        "reservation_confirmed": "Votre réservation pour {party_size} personnes le {date_short} à {time} est confirmée. Merci, {name}! {menu}",
        "reservation_full": "Je suis désolée, mais nous sommes complets à ce moment-là. Le premier créneau disponible est à {available_time}.",
        "last_reservation_time_exceeded": "Désolé, la dernière réservation pour le dîner est à 21h30. Souhaitez-vous réserver pour cette heure-là?",
        "cancel_prompt": "Pour annuler votre réservation, pourriez-vous me donner le nom ou le numéro de téléphone associé?",
        "reservation_cancelled": "Votre réservation a été annulée. Nous espérons vous revoir bientôt.",
        "reservation_not_found": "Je n'ai trouvé aucune réservation avec ces informations.",
        "ask_modification_details": "Pour modifier votre réservation, pourriez-vous me donner le nom ou le numéro de téléphone?",
        "reservation_modified": "Votre réservation a été modifiée avec succès.",
        "full_menu_info": "Le menu complet et la carte des vins sont sur le site web : netlify.app/tibino-menu"
    }
}
